### PR TITLE
added dataloader for SFBD

### PR DESCRIPTION
**Pull request by dibyadas**
@sangeet259 
Run the dataloader notebook and notice the slowness of the code where the one_hot_encodify is running. Took 4-5s in my PC. This really seems unfeasible. We have to think of an alternative.

### CODE REVIEW

**Comment by sangeet259** [comment]
```
CPU times: user 1.11 s, sys: 7.31 ms, total: 1.12 s
Wall time: 1.12 s
```
Seems legit!

**Comment by dibyadas** [comment]
Is it for one execution of one_hot_encodify ?  It's not feasible then. Do you remember last time how much time it was taking to run per image?

**Comment by dibyadas** [comment]
@sangeet259 ?

**Comment by sangeet259** [comment]
@dibyadas 
Yep it's time for one execution, last time it took almost the same time!
Let's optimise this one, I tried searching for one on the web, but couldn't finad any.

If we are not able to optimize this, we will see PASCAL VOC.

**Comment by sangeet259** [comment]
@dibyadas  We are supplied with a `regions.txt` of each image which is a labels map for each pixel.
I have split the `regions.txt` for each image into **8** `.txt`s and saved them.
This way we can access the raw data directly in `__getitem__` and not have to do the preprocessing there.

**Comment by sangeet259** [comment]
@dibyadas  We are supplied with a `regions.txt` of each image which is a labels map for each pixel.
But we need a one_hot_encodified version of it. I did this, now we just have to do 
```python
np.loadtxt("OHE_Vesion_of_image_xyz.txt")  #OHE = One Hot Encoding 
```
 in the ` __getitem__()`
This creates 560 *txt* files for 560 images, which takes up ~ 8.5 GB of space, but since most of the data are redundant (just filled with zeros), a tar compression brings it down to just 26 MB. :tada:

**Comment by sangeet259** [comment]
Better idea, I just saved it with `.npy` and it gave a way better result.
I am trying `h5py` format.

**Comment by dibyadas** [comment]
Awesome! Go ahead and tell me the results soon. 😄

**Comment by sangeet259** [comment]
```
CPU times: user 3.85 ms, sys: 3.97 ms, total: 7.82 ms
Wall time: 9.47 ms
```
:tada:

**Comment by sangeet259** [comment]
Review the commit, and will merge it then
@dibyadas

**Pull request merged**
